name: "Jenkins"
description: "Start Jenkins jobs and update status"
author: "Josh Levy-Kramer"
inputs:
  url:
    description: "Jenkins URL including http/https protocol"
    required: true
  job_name:
    description: "Jenkins job name to build"
    required: true
  username:
    description: "Jenkins username"
    required: false
  api_token:
    description: "Jenkins API token"
    required: false
  parameters:
    description: 'Build parameters in JSON format e.g. `{"field1":"value1"}`'
    required: false
  cookies:
    description: 'Cookies to include in HTTP requests in JSON format e.g. `{"field1":"value1"}`'
    required: false
  wait:
    description: "Should the runner wait for the build to finish and provide ok status"
    required: false
  timeout:
    description: "Timeout in seconds for build to complete"
    required: false
  start_timeout:
    description: "Timeout in seconds for build to start"
    required: false
  interval:
    description: "How frequently in seconds to query Jenkins for build status"
    required: false
outputs:
  build_url:
    description: "Jenkins build URL"
runs:
  using: "docker"
  image: "Dockerfile"
